[project]
name = "fastapi-example"
version = "0.1.0"
requires-python = "==3.14.*"
dependencies = [
    "fastapi[standard]==0.115.6",
    "greenlet>=3.2",
    "sqlalchemy==2.0.37",
    "asyncpg==0.30.0",
    "psycopg_pool==3.2.4",
]

[tool.uv]
package = false
